Upgrade RSpec dependency to ~> 2.13.0.
Older versions of RSpec appear to contain bugs, which cause the tests to fail like this:

  6) ANSI2HTML::Main white bold boys have more fun
       Failure/Error: Unable to find matching line from backtrace
            undefined method `run_all' for []:Array
                 # /Users/hongli/.rvm/gems/ruby-1.9.3-p429/gems/rspec-core-2.3.1/lib/rspec/core/hooks.rb:116:in `run_hook_filtered'